version: '3.8'

services:
  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data
    restart: unless-stopped
    depends_on:
      - mosquitto
    networks:
      - casa_net

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
    networks:
      - casa_net

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - casa_net

  flask-backend:
    build: ./flask-backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - casa_net
    depends_on:
      - mosquitto
      - mongo

networks:
  casa_net:
    driver: bridge